Iter18
MagicNetLab/ya-practicum-shortener pull request #21
Opened 2024-10-06 06:52 UTC by MagicNetLab

2024-10-08 17:12 UTC, nburunova requested changes

2024-10-08 17:12 UTC, nburunova commented on internal/app/server/param.go
> +	// SetDefaultHost(host string, port string) error
закомиченый код лучше не оставлять , иначе захламляется репозиторий

2024-10-08 17:12 UTC, nburunova commented on internal/app/storage/local/interface.go
> +type CacheStoreInterface interface {
интерфейс в го объявляется там , где используется. Нужно перенести объявление этого интерфейса туда, где он нужен

2024-10-08 17:12 UTC, nburunova commented on internal/app/storage/postgres/type.go
> +		con, err := pgx.Connect(context.Background(), s.connectString)
в методы нужно передавать кнтекст первым аргументом и дальше в фукнции его использовать.  context.Background() обычно вызывается где-то в районе main и передается дальше дочерним фукнциям. 
https://pkg.go.dev/context#Background - It is typically used by the **main function,** initialization, and tests, and as the top-level Context for incoming requests. 
Передача контекста первым аргументом нужна для того, чтобы иметь возможность управлять выполнением метода: отменять его, назначать дедлайн из вне. В этом файле ты назначаешь дедлайн 3 секунды, а что если пользователь метода хочет 10 сек или 1 сек? Нужно дать ему эту возможность, принимая  ctx  в качестве аргумента, а не создавая его внутри метода

2024-10-08 17:12 UTC, nburunova commented on internal/app/storage/postgres/type.go
> +func (s *store) PutLink(link string, short string, userID int) error {
ctx первым аргументом

2024-10-08 17:12 UTC, nburunova commented on internal/app/storage/storage.go
> +	var store ILinkStore
в го не принятно использовать в названии I или Inteeface , в названии интерфейсов используется суффикс -er. Посмотри библиотечные интерфейсы, они называются типа Reader, Writer, Closer

2024-10-08 17:12 UTC, nburunova commented on internal/app/storage/type.go
> +type ILinkStore interface {
не обязательно выделять в отдельный файл, интерфейсы обычно объявляются там, где используются. Перенеси объявление интерфейса туда, где он непосредственно нужен

2024-10-09 07:40 UTC, MagicNetLab commented on internal/app/server/param.go
> +	// SetDefaultHost(host string, port string) error
недорефакторинг :)

2024-10-09 07:40 UTC, MagicNetLab commented on internal/app/storage/local/interface.go
> +type CacheStoreInterface interface {
он тут вообще лишний :)

2024-10-09 07:54 UTC, MagicNetLab commented on internal/app/storage/postgres/type.go
> +func (s *store) PutLink(link string, short string, userID int) error {
Не совсем пока вижу смысл его тут передавать извне. Контекст с таймаутом будет создан внутри. Возможно есть сценарии при которых он понадобится но я их пока не вижу и преждевременной оптимизацией не охото заниматься :)

2024-10-09 07:56 UTC, MagicNetLab commented on internal/app/storage/storage.go
> +	var store ILinkStore
Где-то читал что допустимо если с er совсем коряво или не прилично звучит.

2024-10-09 07:59 UTC, MagicNetLab commented on internal/app/storage/type.go
> +type ILinkStore interface {
Подсмотрел многие выносят интерфейсы и типы в отдельный файл. Код становится читабельнее и менее портянистый. Для компилятора фиолетово а человеку проще пр таком подходе работать с кодом.

2024-10-09 08:03 UTC, MagicNetLab commented on internal/app/storage/postgres/type.go
> +		con, err := pgx.Connect(context.Background(), s.connectString)
пропустил эту заглушки при рефакторинге

2024-10-10 17:34 UTC, nburunova commented on internal/app/storage/postgres/type.go
> +func (s *store) PutLink(link string, short string, userID int) error {
это не преждевременная оптимизация, там где нужен контекст, принимаем его снаружи, чтобы тот, кто вызывает нашу фукнкцию могу управлять её выполнением через ctx. Создавая context.Background внтури - признак будущей проблемы.

2024-10-10 17:35 UTC, nburunova commented on internal/app/storage/type.go
> +type ILinkStore interface {
ок

2024-10-12 01:46 UTC, merged