Iter23
MagicNetLab/ya-practicum-shortener pull request #26
Opened 2024-11-11 12:16 UTC by MagicNetLab

os signals

2024-11-12 16:52 UTC, nburunova requested changes

2024-11-12 16:52 UTC, nburunova commented on internal/app/server/server.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
minor: я бы этот контекст назвала ctxForShutdown или как-то так, чтобы не путать с ctx, что объявлен выше

2024-11-12 16:52 UTC, nburunova commented on internal/app/server/server.go
> +	stop()
stop вызывается выше через defer, зачем тут вызывать отдельно?

2024-11-12 16:52 UTC, nburunova commented on internal/app/server/server.go
> +		cancel()
cancel вызывается выше через defer, зачем тут вызывать отдельно?

2024-11-12 16:52 UTC, nburunova commented on internal/app/server/server.go
> +		serv := server
тут зачем вводить еще одну переменную serv? нельзя переменной server пользоваться?

2024-11-12 16:52 UTC, nburunova commented on internal/app/server/server.go
> +		runServers = append(runServers, server)
изменение глобальной переменной тут норм, так как её будет изменять или runHTTPServer или runHTTPSServer (нет других функций, которые изменяют эту переменную и эти функции не могут быть вызваны одновременно). Но более хорошим кодом будет считаться возврат слайса []*http.Server из  runHTTPServer \ runHTTPSServer , и таким образом уйдем от изменения глобальной переменной. И список получаемых сервисов будет более нагляден - сразу видим, что сервисы формируют функции runHTTPServer \ runHTTPSServer, и никто другой. Сейчас, когда смотрим main остается только явно смотреть код по всему пакету, чтобы убедиться, какие функции меняют список сервисов

2024-11-12 16:52 UTC, nburunova commented on internal/app/server/tls.go
> +			Organization: []string{"Roga&Kopita"},
может хотя бы из env брать , а не хардкодить намертво? :)

2024-11-12 16:52 UTC, nburunova commented on internal/app/storage/postgres/type.go
> +	// todo сделать нормально закрытие коннектов к базе.
давай сделаем этот todo

2024-11-12 16:52 UTC, nburunova commented on internal/app/storage/postgres/type.go
> +	// todo отрефакторить и избавиться от постоянных подключений к БД (держать канал).
давай сделаем этот todo

2024-11-12 16:52 UTC, nburunova commented on internal/config/config.go
> +func setDefaultParams() {
костылей для тестов быть не должно. В описаниях заданий были указаны дефолтные параметры.

2024-11-12 16:52 UTC, nburunova commented on internal/config/envreader/env.go
> +	baseHost = strings.Replace(baseHost, "http://", "", 1)
можно проверять, что в env корректный адрес хоста. Если нет, то возвращать ошибку или логировать и задавать дефолтное значение

2024-11-12 16:52 UTC, nburunova commented on internal/config/envreader/env.go
> +	baseHost = strings.Replace(baseHost, "http://", "", 1)
в комментарии к коду лучше указать, в каком формате ожидается хост, от каких ошибочных данных защищает этот replace. Комментарии в коде должны быть содержательными.

2024-11-12 16:52 UTC, nburunova commented on internal/config/flagsreader/flags.go
>  	flag.StringVar(&defaultHost, defaultHostKey, "", "Base address")
задай какие-то значения для флагов. Сейчас у тебя третий аргумент - пустые строки. В третьем аргументе, как мне помнится, задаются дефолтные значения для флага. То есть если пользователь явно не передал флаг в командной строке запуска, то подставляется дефолтное значение. Дефолтные значения у тебя выше по коду были как раз определены и обозначенные как костыль к тестам.

2024-11-12 16:52 UTC, nburunova commented on internal/config/jsonreader/type.go
> +	return true
всегда true будет возвращаться, это верно? Может иногда false нужно возращает? Если тут должно всегда true возвращаться, то может и не нужен этот метод? не стоит его вызывать, если заранее знаем, что там будет true

2024-11-12 16:52 UTC, nburunova commented on internal/config/type.go
> +type AppConfig interface {
нужен ли этот интерфейс? Может просто напрямую объект Configurator  использовать ? Интерфейс лишний имхо

2024-11-12 16:52 UTC, nburunova commented on internal/config/type.go
> +type ParamsReader interface {
снужен ли этот интерфейс? Может просто напрямую объект configParams использовать (сделав его публичным) ? Интерфейс лишний имхо.
Интерфейсы ведь не бесплатные, тратиться время и память для нахождения нужного метода у объекта

2024-11-16 13:41 UTC, MagicNetLab commented on internal/app/server/server.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+

2024-11-16 13:42 UTC, MagicNetLab commented on internal/app/server/server.go
> +	stop()
недорефакторинг

2024-11-16 13:43 UTC, MagicNetLab commented on internal/app/server/server.go
> +		cancel()
недорефакторинг

2024-11-16 13:54 UTC, MagicNetLab commented on internal/app/server/server.go
> +		serv := server
при запуске работы с короткими ссылками и обработки переходов по ним на разных хостах/портах по другому работать не будет. в горутину передается не то что должно.

2024-11-17 02:48 UTC, MagicNetLab commented on internal/app/server/server.go
> +		runServers = append(runServers, server)
Вернуть слайс серверов тут не достаточно. У http и https разная логика запуска и потребуется возвращать дополнительный флаг http/https и сертификаты для запуска с tls. На мой взгляд усложнение дополнительным ветвлением функции Run() не стоит того. На счет удобства стения кода тут еще можно подумать но пока стоящих решений не вижу.

2024-11-17 03:04 UTC, MagicNetLab commented on internal/config/envreader/env.go
> +	baseHost = strings.Replace(baseHost, "http://", "", 1)
+

2024-11-17 03:26 UTC, MagicNetLab commented on internal/config/flagsreader/flags.go
>  	flag.StringVar(&defaultHost, defaultHostKey, "", "Base address")
Поправил объявление переменных чтобы они были единообразными. По поводу дефолтных параметров - в нашем случае они тут не уместны. В задачи ридера входит только считать и передать результат в пакет  config. По скольку конфиги собираются из 3 разных источников имеющих разные приоритеты то интерпритация значений из ридеров и установка дефолтных значений целиком и полностью обязанность пакета config.

2024-11-17 03:31 UTC, MagicNetLab commented on internal/config/jsonreader/type.go
> +	return true
Метод интерфейсный, его реализация обязательна. Логика обрабоки json файла такова что в enable_https всегда будет bool и не получится определить был он в файле или нет. Поэтому тут всегда возвращается true.

2024-11-17 03:51 UTC, MagicNetLab commented on internal/config/type.go
> +type AppConfig interface {
А какой из 3-х конфигураторов использовать? AppConfig это результат склеивания дефолтных параметров и данных из 3-разных источников. Как минимум у него все значения установлены и геттеры не могу вернуть ошибку. AppConfig и configurator объекты разных уровней с разной зоной ответственности. Возможно в парадигме "говей" это кажется лишним но это нормальное разделение ответственности между объектами. Есть вероятность что когда я в полной мере познаю дзен "говей" то перепишу этот кусок кода но пока я считаю его правильным. :)

2024-11-17 03:56 UTC, MagicNetLab commented on internal/config/type.go
> +type ParamsReader interface {
Интерфейс нужен для правильной и единообразной работы пакета config с плагинами-ридерами. Без него код станет жутко длинным и не читаемым с кучей "if" и прочих конструкций. Без него можно обойтись если количество плагинов 1-2, но когда их становится больше ту нужна универсализация... если не охото через пару месяцев разбиться лбом о стену пытая прочитать и понять длинный лапшекод. :)

2024-11-17 09:20 UTC, MagicNetLab commented on internal/config/type.go
> +type AppConfig interface {
Вероятно не сразу понял о чем речь. Возвращать сразу структуру а не интерфейс... Ну так привычка работать через интерфейсы :)

2024-11-19 09:19 UTC, nburunova approved these changes

2024-11-20 11:22 UTC, merged