Iter25
MagicNetLab/ya-practicum-shortener pull request #28
Opened 2024-12-12 14:22 UTC by MagicNetLab

grpc server

2024-12-21 17:18 UTC, bulbetski commented
Типичная структура golang проекта с grpc.

```
grpc-project/
├── api/
│   ├── proto/
│   │   ├── your_service.proto       # Прото-описание для gRPC сервисов
│   │   ├── another_service.proto    # Дополнительные proto-файлы
│   │   └── generate_protos.sh       # Скрипт для генерации gRPC кода
├── cmd/
│   ├── server/
│   │   └── main.go                  # Точка входа для gRPC сервера
│   ├── client/
│   │   └── main.go                  # Пример gRPC клиента для тестирования
├── config/
│   ├── config.yaml                  # Конфигурационный файл
│   └── config.go                    # Загрузчик конфигурации
├── internal/
│   ├── service/
│   │   ├── your_service.go          # Реализация бизнес-логики для gRPC сервисов
│   │   └── another_service.go       # Дополнительная бизнес-логика
│   ├── usecase/
│   │   ├── your_service_usecase.go  # Юз-кейсы для вашего сервиса
│   │   └── another_usecase.go       # Дополнительные юз-кейсы
│   ├── repository/
│   │   ├── repository.go            # Определение интерфейсов репозиториев
│   │   ├── redis_repository.go      # Реализация для Redis
│   │   └── sql_repository.go        # Реализация для SQL
│   └── models/
│       └── models.go                # Дата-модели и DTO
├── pkg/
│   ├── your_service/
│   │   ├── your_service.pb.go       # Сгенерированный gRPC-код
│   │   ├── your_service_grpc.pb.go  # Сгенерированные сервер и клиент gRPC
│   │   └── another_service.pb.go    # Сгенерированные дополнительные файлы
│   ├── logger/
│   │   └── logger.go                # Утилита для логирования
│   ├── middleware/
│   │   └── grpc_middleware.go       # Middleware для gRPC (например, логирование, аутентификация)
│   └── utils/
│       └── utils.go                 # Общие утилиты (например, валидация, хелперы)
├── scripts/
│   ├── migrate_db.sh                # Скрипты миграции базы данных
├── go.mod                           # Go module файл
├── go.sum                           # Файл блокировки зависимостей
└── README.md                        # Документация проекта
```

2024-12-21 19:09 UTC, bulbetski requested changes
В целом написано хорошо, но есть моменты, которые нужно исправить (например с in-memory хранилищем)

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/memory/memory.go
> +	users []UserEntity
in-memory хранилища должны быть выполнены при помощи map, чтобы была возможность доступа к данным за константное время. 
Можно сделать map[string]UserEntity, где ключ это логин. Тогда не придется итерировать по юзерам, а получить сразу же из мапы по логину.

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/memory/memory.go
> +	}
в таком случае maxID стоит сделать полем структуры Store, чтобы каждый раз не итерировать

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/memory/memory.go
> +	}
убрать цикл посредством использования мапы

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/memory/memory.go
> +	}
убрать цикл посредством использования мапы

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/postgres/type.go
> +	createUser                = "INSERT INTO users (login, secret) VALUES ($1, $2)"
Вкусовщина, но я бы запросы as is писал в месте их использования

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/postgres/type.go
>  const (
Все методы находятся в файле type.go 
Надо переименовать по названию сущности с которой работают методы из файла

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/postgres/type.go
> +		if errors.Is(err, pgx.ErrNoRows) {
Ошибка pgx.ErrNoRows невозможна при использовании COUNT в запросе, так как запрос всегда возвращает результат (хотя бы 0).

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/postgres/type.go
> +	}
При INSERT INTO с фиксированным значением полей и без ON CONFLICT или других модификаций, RowsAffected() всегда возвращает 1, если запрос выполнен успешно. Если что-то пошло не так, ошибка будет возвращена самим Exec. Проверка избыточна и может быть удалена.

2024-12-21 19:09 UTC, bulbetski commented on internal/app/repo/repo.go
>  var driver Driver
Почему называется driver? Это интерфейс репозитория. Драйвер базы данных — это программное обеспечение, которое обеспечивает взаимодействие приложения с конкретной СУБД

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/grpc/grpc.go
> +	resultLinks := make([]*pb.EncodeBatchLinksResponseEntity, len(links))
Ты создаешь слайс resultLinks с фиксированной длиной, а затем добавляете элементы через append. Это приводит к добавлению пустых элементов в начале. Надо сделать вот так:
```
resultLinks := make([]*pb.EncodeBatchLinksResponseEntity, 0, len(links))
```

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/grpc/grpc.go
> +		short := shortgen.GetShortLink(7)
Возможно надо генерировать короткий УРЛ до тех пор пока не сгенерируем уникальный?

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/grpc/grpc.go
> +	go link.BatchDeleteLinks(ctx, r.GetShort(), int(userID))
внутри и без того вызывается горутина

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/rest/web_test.go
> +			token, _ := jwttoken.GenerateToken(int64(tt.userID), c.GetJWTSecret())
не обрабатываем ошибки

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/rest/web_test.go
> +		token, _ := jwttoken.GenerateToken(int64(userID), c.GetJWTSecret())
не обрабатываем ошибку

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/server.go
>  var runServers []*http.Server
Использование глобальной переменной runServers для хранения запущенных HTTP-серверов затрудняет тестирование и делает код менее предсказуемым.
Передавай список серверов через структуру или возвращай их из функций runHTTPServer и runHTTPSServer

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/server.go
>  func getListeners() listeners {
Код для запуска pprof сервера дублируется в функциях runHTTPServer и runHTTPSServer.

func runPProfServer(pprofHost string) *http.Server {}

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/server.go
> +func runGRPCServer(configurator configurator) *grpc.Server {
configurator не используется

2024-12-21 19:09 UTC, bulbetski commented on internal/app/server/server.go
> +	listen, err := net.Listen("tcp", ":3200")
хардкод grpc порта, надо брать из env переменной, добавить в condigurator метод GetGRPCPort

2024-12-21 19:09 UTC, bulbetski commented on internal/service/jwttoken/token.go
> +		})
Логика проверки метода подписи (SigningMethodHMAC) дублируется в функциях ValidateToken и GetUserIDFromToken

2024-12-21 19:09 UTC, bulbetski commented on internal/service/link/link.go
> +		}
можно сделать, чтобы GetShort сразу возвращал конфликтующий URL при помощи ON CONFLICT

2024-12-21 19:09 UTC, bulbetski commented on internal/service/link/link.go
> +				}
Нужно удалить default. case'ы будут всё равно висеть в цикле for, а default будет замедлять обработку

2024-12-21 19:09 UTC, bulbetski commented on internal/service/link/link.go
> +				select {
Нужно обрабатывать отмену родительского контекста во всех селектах.

2024-12-21 19:09 UTC, bulbetski commented on internal/service/user/user.go
> +	return hex.EncodeToString(b), nil
Метод randString генерирует строки длиной в два раза больше заданного числа n (из-за кодировки в hex.EncodeToString)

return hex.EncodeToString(b)[:n], nil

2025-01-05 05:47 UTC, MagicNetLab commented on internal/service/link/link.go
> +		}
вот тут не понял задумку :(

2025-01-05 05:54 UTC, MagicNetLab commented on internal/app/repo/postgres/type.go
>  const (
тоже немного смущало. вынес отдельно но все равно пока не нравится... подумаю еще на досуге как тут все раскидать.

2025-01-05 06:03 UTC, MagicNetLab commented on internal/app/repo/repo.go
>  var driver Driver
кто бы знал. в тот момент показалось логичным такое название. :)

2025-01-05 06:17 UTC, MagicNetLab commented on internal/app/server/grpc/grpc.go
> +	go link.BatchDeleteLinks(ctx, r.GetShort(), int(userID))
по заданию нам не надо дожидаться окнчания выполнения а если запустить без go то будем ждать пока удаляться все ссылки.

2025-01-26 01:36 UTC, bulbetski commented on internal/service/link/link.go
> +		}
Вот такой запрос позволит вернуть дубликат. Мы делай update set строчки значениями из этой же строчки (да, звучит костыльно, но так постгрес работает). Если же дубликата нет, то вернем новую запись 
```
INSERT INTO table_name (id, col1) VALUES (1, 'A')
ON CONFLICT (id) DO UPDATE SET col1 = EXCLUDED.col1
RETURNING *;
```

2025-01-26 01:37 UTC, bulbetski approved these changes
Всё супер исправил, сори за задержку. В след раз пингуй меня если 1-2 дня задержка, а то задачи так теряются

2025-01-26 12:38 UTC, merged